# protocol
port: 8374
recv_buffer_size: 128000

# mutual-tls usage
use_mtls: true
mtls_certificate_path: tests/certs/client/client-cert.pem
mtls_certificate_key_path: tests/certs/client/client-cert-key.pem

# trusted CA certificate path
ca_certificate_path: tests/certs/normal_ca/normal-ca.pem

server_hostname: 127.0.0.1