# protocol
port: 8374
recv_buffer_size: 128000

# mutual-tls usage
use_mtls: true
mtls_trusted_ca_certificate_path: tests/certs/mtls_ca/mtls-ca.pem

# tls certificates to load as own
certificate_key_path: tests/certs/server/server-cert-key.pem
certificate_path: tests/certs/server/server-cert.pem

# communication models to be supported by the server at runtime
supported_models:
  sc_model: true
  rbg_model: false
  ubg_model: false

# settings for each model
